name: Publish Docker Image

on:
  release:
    types:
      - published

jobs:
  docker-publish:
    name: 'Build and publish Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: |
          (git describe --tags --exact-match \
            || git symbolic-ref -q --short HEAD \
            || git rev-parse --short HEAD) > version.txt 2> /dev/null

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            latest
            alpine
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=n1try/wakapi:buildcache-alpine
          cache-to: type=registry,ref=n1try/wakapi:buildcache-alpine,mode=max
